name: Ubuntu Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y git gcc g++ cmake python3 make ninja-build
          sudo apt-get install -y libgsl-dev libxml2-dev

      - name: Configure ns-3
        run: ./ns3 configure --disable-tests --disable-examples -G"Ninja"

      - name: Build ns-3
        run: ./ns3 build
