#!/usr/bin/env python3
"""
Analyze whether the serving satellite is receding when servingSnrTrend < -1.5 fires.

Supported inputs:
  1. CSV generated by the simulation instrumentation:
     result/tdcho/serving_snr_trigger_analysis.csv
  2. Existing text logs containing [HO_DEBUG] lines, where serving distance trend
     is reconstructed from consecutive serving_dist samples for the same UE/cell.

Outputs:
  - Summary to stdout
  - Optional summary text file
"""

import argparse
import re
from pathlib import Path
from typing import Iterable, Optional

import pandas as pd


DEFAULT_RESULT_DIR = Path(__file__).resolve().parents[2] / "result" / "tdcho"

REQUIRED_COLUMNS = [
    "time",
    "ueId",
    "servingCellId",
    "bestNeighborCellId",
    "servingSnrTrend",
    "servingDistanceTrend",
    "servingIsReceding",
    "servingSinr",
    "servingDistance",
    "neighborSnrTrend",
    "neighborDistanceTrend",
    "neighborSinr",
    "neighborDistance",
    "dynamicMarginBeforeClamp",
]


def fmt_ratio(count: int, total: int) -> str:
    if total == 0:
        return f"{count}/{total} = n/a"
    return f"{count}/{total} = {count / total * 100.0:.2f}%"


def load_csv(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    if df.empty:
        raise ValueError("CSV is empty")

    missing = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError("Missing columns: " + ", ".join(missing))

    return df


def parse_ho_debug_logs(log_paths: Iterable[Path], threshold: float, measurement_period: float) -> pd.DataFrame:
    pattern = re.compile(
        r"\[HO_DEBUG\],ue=(?P<ue>\d+),t=(?P<time>[-\d.]+),"
        r"serving=(?P<serving>.*?),neighbor=(?P<neighbor>.*?),"
        r"serving_sinr=(?P<serving_sinr>[-\d.]+),neighbor_sinr=(?P<neighbor_sinr>[-\d.]+),"
        r"serving_trend=(?P<serving_trend>[-\d.]+),neighbor_trend=(?P<neighbor_trend>[-\d.]+),"
        r"serving_dist=(?P<serving_dist>[-\d.]+),neighbor_dist=(?P<neighbor_dist>[-\d.]+),"
        r"neighbor_dist_trend=(?P<neighbor_dist_trend>[-\d.]+),dynamic_margin=(?P<dynamic_margin>[-\d.]+),"
    )

    rows = []

    for log_path in log_paths:
        if not log_path.exists():
            continue

        last_seen = {}
        with log_path.open(errors="ignore") as handle:
            for line in handle:
                match = pattern.search(line)
                if not match:
                    continue

                ue_id = int(match["ue"])
                sim_time = float(match["time"])
                serving_cell = match["serving"]
                serving_dist = float(match["serving_dist"])
                serving_trend = float(match["serving_trend"])
                key = (ue_id, serving_cell)

                if serving_trend < threshold:
                    serving_dist_trend = 0.0
                    prev = last_seen.get(key)
                    if prev is not None:
                        prev_time, prev_dist = prev
                        if abs(sim_time - prev_time - measurement_period) < 1e-6:
                            serving_dist_trend = serving_dist - prev_dist

                    rows.append(
                        {
                            "time": sim_time,
                            "ueId": ue_id,
                            "servingCellId": serving_cell,
                            "bestNeighborCellId": match["neighbor"],
                            "servingSnrTrend": serving_trend,
                            "servingDistanceTrend": serving_dist_trend,
                            "servingIsReceding": int(serving_dist_trend > 0.0),
                            "servingSinr": float(match["serving_sinr"]),
                            "servingDistance": serving_dist,
                            "neighborSnrTrend": float(match["neighbor_trend"]),
                            "neighborDistanceTrend": float(match["neighbor_dist_trend"]),
                            "neighborSinr": float(match["neighbor_sinr"]),
                            "neighborDistance": float(match["neighbor_dist"]),
                            "dynamicMarginBeforeClamp": float(match["dynamic_margin"]),
                            "sourceLog": str(log_path),
                        }
                    )

                last_seen[key] = (sim_time, serving_dist)

    if not rows:
        raise ValueError("No trigger events found in the provided HO_DEBUG logs")

    return pd.DataFrame(rows)


def analyze_frame(
    df: pd.DataFrame,
    out_summary: Optional[Path] = None,
    source_label: str = "unknown",
) -> int:
    if df.empty:
        print("Input data is empty")
        return 2

    df["servingIsReceding"] = df["servingIsReceding"].astype(int)

    total = len(df)
    receding = int(df["servingIsReceding"].sum())
    approaching_or_flat = total - receding
    approaching = int((df["servingDistanceTrend"] < 0.0).sum())
    flat = int((df["servingDistanceTrend"] == 0.0).sum())

    lines = []
    lines.append("Serving SNR Trigger Analysis")
    lines.append("============================")
    lines.append("")
    lines.append(f"Source: {source_label}")
    lines.append("Condition analyzed: servingSnrTrend < -1.5")
    lines.append("Receding definition: servingDistanceTrend > 0")
    lines.append("")
    lines.append("[1] Overall probability")
    lines.append("---")
    lines.append(f"Total trigger events: {total}")
    lines.append(f"P(serving satellite is receding | servingSnrTrend < -1.5) = {fmt_ratio(receding, total)}")
    lines.append(f"Non-receding events = {fmt_ratio(approaching_or_flat, total)}")
    lines.append("")
    lines.append("[2] Distance trend breakdown")
    lines.append("---")
    lines.append(f"Approaching (servingDistanceTrend < 0): {fmt_ratio(approaching, total)}")
    lines.append(f"Receding   (servingDistanceTrend > 0): {fmt_ratio(receding, total)}")
    lines.append(f"Flat       (servingDistanceTrend = 0): {fmt_ratio(flat, total)}")
    lines.append("")
    lines.append("[3] Trigger context averages")
    lines.append("---")
    lines.append(f"Mean servingSnrTrend: {df['servingSnrTrend'].mean():.4f}")
    lines.append(f"Mean servingDistanceTrend: {df['servingDistanceTrend'].mean():.4f}")
    lines.append(f"Mean servingSinr: {df['servingSinr'].mean():.2f}")
    lines.append(f"Mean neighborSinr: {df['neighborSinr'].mean():.2f}")
    lines.append(f"Mean dynamicMarginBeforeClamp: {df['dynamicMarginBeforeClamp'].mean():.2f}")
    lines.append("")

    per_ue = (
        df.groupby("ueId")
        .agg(
            triggerEvents=("ueId", "size"),
            recedingEvents=("servingIsReceding", "sum"),
            meanServingSnrTrend=("servingSnrTrend", "mean"),
            meanServingDistanceTrend=("servingDistanceTrend", "mean"),
        )
        .reset_index()
        .sort_values("ueId")
    )
    per_ue["recedingProbabilityPct"] = per_ue.apply(
        lambda row: (row["recedingEvents"] / row["triggerEvents"] * 100.0)
        if row["triggerEvents"] > 0 else 0.0,
        axis=1,
    )

    lines.append("[4] Per-UE breakdown")
    lines.append("---")
    for _, row in per_ue.iterrows():
        lines.append(
            "UE {ue}: receding {rec}/{total} ({pct:.2f}%), "
            "meanServingSnrTrend={snr:.4f}, meanServingDistanceTrend={dist:.4f}".format(
                ue=int(row["ueId"]),
                rec=int(row["recedingEvents"]),
                total=int(row["triggerEvents"]),
                pct=row["recedingProbabilityPct"],
                snr=row["meanServingSnrTrend"],
                dist=row["meanServingDistanceTrend"],
            )
        )

    report = "\n".join(lines)
    print(report)

    if out_summary is not None:
        out_summary.write_text(report)
        print(f"Wrote summary to: {out_summary}")

    return 0


def analyze(
    csv_path: Optional[Path],
    log_paths: Iterable[Path],
    threshold: float,
    measurement_period: float,
    out_summary: Optional[Path] = None,
) -> int:
    try:
        if csv_path is not None:
            df = load_csv(csv_path)
            return analyze_frame(df, out_summary, source_label=str(csv_path))

        log_paths = list(log_paths)
        if not log_paths:
            print("Error: no log files provided")
            return 2

        df = parse_ho_debug_logs(log_paths, threshold, measurement_period)
        return analyze_frame(
            df,
            out_summary,
            source_label=", ".join(str(p) for p in log_paths),
        )
    except (FileNotFoundError, ValueError) as exc:
        print(f"Error: {exc}")
        return 2


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Analyze servingSnrTrend trigger events from CSV or HO_DEBUG logs"
    )
    parser.add_argument(
        "--csv",
        "-c",
        default=str(DEFAULT_RESULT_DIR / "serving_snr_trigger_analysis.csv"),
        help="Path to serving_snr_trigger_analysis.csv",
    )
    parser.add_argument(
        "--log",
        "-l",
        action="append",
        default=[],
        help="Path to a text log containing HO_DEBUG lines; can be repeated",
    )
    parser.add_argument(
        "--threshold",
        type=float,
        default=-1.5,
        help="Trigger threshold for servingSnrTrend when parsing logs",
    )
    parser.add_argument(
        "--measurement-period",
        type=float,
        default=1.0,
        help="Measurement period used to reconstruct serving distance trend from logs",
    )
    parser.add_argument(
        "--out",
        "-o",
        default=str(DEFAULT_RESULT_DIR / "serving_snr_trigger_summary.txt"),
    )
    args = parser.parse_args()

    csv_path = Path(args.csv) if args.csv else None
    log_paths = [Path(p) for p in args.log]
    raise SystemExit(
        analyze(
            csv_path=csv_path,
            log_paths=log_paths,
            threshold=args.threshold,
            measurement_period=args.measurement_period,
            out_summary=Path(args.out),
        )
    )
